version: "3.4"

services:
  angularbootstrapplayground:
    image: abp-image
    container_name: abp-container
    build: 
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "4202:80"
    restart: always
