name: CI

on:
  push:
    branches: [ main, dev, feature/* ]
  pull_request:
    branches: [ main, dev, feature/* ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:  
  build:    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with: 
        node-version: ${{ matrix.node-version }}

    - uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}  

    - uses: actions/cache@v3    
      with:
        path: .husky
        key: husky-${{ hashFiles('.husky/pre-commit') }}

    - name: Install dependencies
      run: npm ci

    - name: Husky
      run: |
        npx husky install
        npx husky add .husky/pre-commit "npx lint-staged"

    - name: Test
      run: npm run test -- --ci
    
    - name: Build
      run: npm run build -- --configuration production

  deploy-feature:
    if: ${{ github.event_name == 'pull_request' }}
    needs: [ build ]
    uses: ./.github/workflows/common_deploy_feature.yaml
    with:
      cf_pages_project: isl-ui-dev
    secrets:
      api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  deploy:
    if: ${{ github.event_name == 'push' }}
    needs: [ build ]
    uses: ./.github/workflows/common_deploy.yaml
    with:
      cf_pages_project: isl-ui-dev
    secrets:
      api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}